# Array	Indexing,	Slicing,	&	Reshaping

In [1]:
import numpy as np

### Indexing

In [2]:
# In 1 D array
arr1d = np.arange(18).astype(np.str_)
arr1d

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17'], dtype='<U11')

In [3]:
arr1d[13]

'13'

In [4]:
# 2d indexing
l = [
    [1, 2, 3],
    [4, 5, 6]
]
l[1][1]

5

In [5]:
arr2d = np.array(l)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d[1][1], arr2d[1, 1]

(5, 5)

In [7]:
# 3d 
l3 = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ]
]
l3[0][1][0]

5

In [8]:
arr3d = np.array(l3)
arr3d[0,1,0]

5

In [9]:
arr3d_2 = np.arange(18).reshape((3, 6, 1))
arr3d_2[1, 4, 0]

10

### slicing

In [10]:
# 1d
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arr[1:5:1]

array([1, 2, 3, 4])

In [12]:
# 2d 
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr[1:3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[1:3:, :2:]

array([[4, 5],
       [7, 8]])

In [15]:
arr = np.arange(36).reshape((6, 6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
arr[::2,  1::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [17]:
arr[4::, 4::]

array([[28, 29],
       [34, 35]])

In [18]:
arr = np.arange(36).reshape((3, 2, 6))
arr

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [19]:
arr[:2:, 1::, 1:5:]

array([[[ 7,  8,  9, 10]],

       [[19, 20, 21, 22]]])

### Reshaping

In [20]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr.reshape((3, 4, 1))

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [23]:
arr.reshape((3, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [24]:
arr4d = arr.reshape((3, 2, 2, 1))
arr4d

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]]])

In [25]:
arr4d.reshape((2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
arr.shape

(12,)

- -1 (minus one) can only be used in only one dimension to automatically determine the number of elements in particular axis.

In [27]:
arr.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:
arr.reshape((-1, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [29]:
arr.reshape((-1, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

- Keeping -1 in multiple position can lead to error

In [30]:
arr.reshape((-1, 2, -1))

ValueError: can only specify one unknown dimension