# Mathematical	&	Statistical	Operations	in	NumPy

In [3]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

np.add(a1, a2)

array([5, 7, 9])

In [5]:
np.subtract(a1, a2)

array([-3, -3, -3])

In [6]:
np.multiply(a1, a2)

array([ 4, 10, 18])

In [7]:
np.divide(a1, a2)

array([0.25, 0.4 , 0.5 ])

In [8]:
np.divmod(a2, a1)

(array([4, 2, 2]), array([0, 1, 0]))

In [9]:
np.sum(np.arange(10))

45

In [10]:
a1 = np.random.randint(1, 100)
a1

98

In [11]:
1e-100

1e-100

In [12]:
np.random.seed(1)
a1 = np.random.random(10)
a1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [13]:
np.mean(a1)

0.3146293077834573

In [14]:
np.mean(
    np.random.random((2, 5))
)

0.41993218627918366

In [15]:
a1 = np.random.random_integers(1, 100, 50)
a1

C:\Users\rajba\AppData\Local\Temp\ipykernel_2392\2216515129.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, 50)


array([14, 10,  8, 64, 62, 23, 58,  2,  1, 61, 82,  9, 89, 14, 48, 73, 31,
       72,  4, 71, 22, 50, 58,  4, 69, 25, 44, 77, 27, 53, 81, 42, 83, 16,
       65, 69, 26, 99, 88,  8, 27, 26, 23, 10, 68, 24, 28, 38, 58, 84])

In [16]:
np.max(a1), np.min(a1)

(99, 1)

In [17]:
np.argmax(a1), np.argmin(a1)

(37, 8)

In [18]:
a1 = np.random.random_integers(1, 100, (5, 5))
a1

C:\Users\rajba\AppData\Local\Temp\ipykernel_2392\2592620425.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, (5, 5))


array([[39,  9, 33, 35, 11],
       [24, 16, 88, 26, 72],
       [93, 75, 63, 47, 33],
       [89, 24, 56, 66, 78],
       [ 4,  1, 78,  7, 53]])

In [19]:
np.max(a1), np.min(a1)

(93, 1)

In [20]:
np.argmax(a1), np.argmin(a1)

(10, 21)

In [21]:
np.unravel_index(np.argmax(a1), a1.shape)

(2, 0)

In [22]:
np.unravel_index(np.argmin(a1), a1.shape)

(4, 1)

In [23]:
np.sqrt(a1)

array([[6.244998  , 3.        , 5.74456265, 5.91607978, 3.31662479],
       [4.89897949, 4.        , 9.38083152, 5.09901951, 8.48528137],
       [9.64365076, 8.66025404, 7.93725393, 6.8556546 , 5.74456265],
       [9.43398113, 4.89897949, 7.48331477, 8.1240384 , 8.83176087],
       [2.        , 1.        , 8.83176087, 2.64575131, 7.28010989]])

In [24]:
np.cbrt(a1)

array([[3.39121144, 2.08008382, 3.20753433, 3.27106631, 2.22398009],
       [2.88449914, 2.5198421 , 4.44796018, 2.96249607, 4.16016765],
       [4.5306549 , 4.21716333, 3.97905721, 3.60882608, 3.20753433],
       [4.4647451 , 2.88449914, 3.82586237, 4.04124002, 4.27265868],
       [1.58740105, 1.        , 4.27265868, 1.91293118, 3.75628575]])

In [25]:
np.log(a1)

array([[3.66356165, 2.19722458, 3.49650756, 3.55534806, 2.39789527],
       [3.17805383, 2.77258872, 4.47733681, 3.25809654, 4.27666612],
       [4.53259949, 4.31748811, 4.14313473, 3.8501476 , 3.49650756],
       [4.48863637, 3.17805383, 4.02535169, 4.18965474, 4.35670883],
       [1.38629436, 0.        , 4.35670883, 1.94591015, 3.97029191]])

In [26]:
np.log10(a1)

array([[1.59106461, 0.95424251, 1.51851394, 1.54406804, 1.04139269],
       [1.38021124, 1.20411998, 1.94448267, 1.41497335, 1.8573325 ],
       [1.96848295, 1.87506126, 1.79934055, 1.67209786, 1.51851394],
       [1.94939001, 1.38021124, 1.74818803, 1.81954394, 1.8920946 ],
       [0.60205999, 0.        , 1.8920946 , 0.84509804, 1.72427587]])

In [27]:
np.log2(a1)

array([[5.28540222, 3.169925  , 5.04439412, 5.12928302, 3.45943162],
       [4.5849625 , 4.        , 6.45943162, 4.70043972, 6.169925  ],
       [6.53915881, 6.22881869, 5.97727992, 5.55458885, 5.04439412],
       [6.47573343, 4.5849625 , 5.80735492, 6.04439412, 6.28540222],
       [2.        , 0.        , 6.28540222, 2.80735492, 5.72792045]])

[Mathematical Functions](https://numpy.org/doc/stable/reference/routines.math.html)<br>
[Statistical Functions](https://numpy.org/doc/stable/reference/routines.statistics.html)