# Mathematical	&	Statistical	Operations	in	NumPy

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

np.add(a1, a2)

array([5, 7, 9])

In [3]:
np.subtract(a1, a2)

array([-3, -3, -3])

In [4]:
np.multiply(a1, a2)

array([ 4, 10, 18])

In [5]:
np.divide(a1, a2)

array([0.25, 0.4 , 0.5 ])

In [7]:
np.divmod(a2, a1)

(array([4, 2, 2]), array([0, 1, 0]))

In [8]:
np.sum(np.arange(10))

45

In [9]:
a1 = np.random.randint(1, 100)
a1

58

In [37]:
1e-100

1e-100

In [38]:
np.random.seed(1)
a1 = np.random.random(10)
a1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [39]:
np.mean(a1)

0.3146293077834573

In [40]:
np.mean(
    np.random.random((2, 5))
)

0.41993218627918366

In [42]:
a1 = np.random.random_integers(1, 100, 50)
a1

C:\Users\rajba\AppData\Local\Temp\ipykernel_6168\2216515129.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, 50)


array([10,  8, 64, 62, 23, 58,  2,  1, 61, 82,  9, 89, 14, 48, 73, 31, 72,
        4, 71, 22, 50, 58,  4, 69, 25, 44, 77, 27, 53, 81, 42, 83, 16, 65,
       69, 26, 99, 88,  8, 27, 26, 23, 10, 68, 24, 28, 38, 58, 84, 39])

In [43]:
np.max(a1), np.min(a1)

(99, 1)

In [44]:
np.argmax(a1), np.argmin(a1)

(36, 7)

In [45]:
a1 = np.random.random_integers(1, 100, (5, 5))
a1

C:\Users\rajba\AppData\Local\Temp\ipykernel_6168\2592620425.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a1 = np.random.random_integers(1, 100, (5, 5))


array([[ 9, 33, 35, 11, 24],
       [16, 88, 26, 72, 93],
       [75, 63, 47, 33, 89],
       [24, 56, 66, 78,  4],
       [ 1, 78,  7, 53, 86]])

In [46]:
np.max(a1), np.min(a1)

(93, 1)

In [47]:
np.argmax(a1), np.argmin(a1)

(9, 20)

In [49]:
np.unravel_index(np.argmax(a1), a1.shape)

(1, 4)

In [50]:
np.unravel_index(np.argmin(a1), a1.shape)

(4, 0)

In [51]:
np.sqrt(a1)

array([[3.        , 5.74456265, 5.91607978, 3.31662479, 4.89897949],
       [4.        , 9.38083152, 5.09901951, 8.48528137, 9.64365076],
       [8.66025404, 7.93725393, 6.8556546 , 5.74456265, 9.43398113],
       [4.89897949, 7.48331477, 8.1240384 , 8.83176087, 2.        ],
       [1.        , 8.83176087, 2.64575131, 7.28010989, 9.2736185 ]])