# Linear	Algebra	with	NumPy

In [1]:
import numpy as np

In [2]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [5]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.diagonal(arr)

array([0, 4, 8])

[
    [1, 2],
    [3, 4]
]
Determinant = 1*4 - 2*3 = -2

In [7]:
arr = np.arange(1, 5).reshape((2,2))
arr

array([[1, 2],
       [3, 4]])

In [8]:
np.linalg.det(arr)

-2.0000000000000004

In [9]:
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.linalg.det(arr)

0.0

In [14]:
arr = np.random.random_integers(0, 10, (3, 3))
arr

C:\Users\rajba\AppData\Local\Temp\ipykernel_6472\1869614447.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  arr = np.random.random_integers(0, 10, (3, 3))


array([[0, 6, 5],
       [5, 5, 5],
       [3, 9, 3]])

In [15]:
np.linalg.det(arr)

149.99999999999997

In [16]:
np.linalg.inv(arr)

array([[-0.2       ,  0.18      ,  0.03333333],
       [ 0.        , -0.1       ,  0.16666667],
       [ 0.2       ,  0.12      , -0.2       ]])

In [ ]:
[[1, 2],
 [3, 4]]

# ---
[[1, 3],
 [2, 4]]

### Transpose
- Converts rows into columns and vice-versa of matrix.

In [17]:
arr = np.arange(1, 5).reshape((2, 2))
arr

array([[1, 2],
       [3, 4]])

In [18]:
arr.T

array([[1, 3],
       [2, 4]])

In [19]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

3x + 6y = 9
3 * (x + 2y) = 3 * 3

A * e_vector = e_values * e_vector

In [21]:
e_val, e_vec = np.linalg.eig(arr)
e_val, e_vec 

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
# 2x + 3y = 10
# x - y = 2

In [22]:
coeff = np.array([
    [2, 3],
    [1, -1]
])
y = np.array([10, 2])

np.linalg.solve(coeff, y)

array([3.2, 1.2])

In [23]:
2 * 3.2 + 3*1.2

10.0

In [24]:
# x + y -2z = 7
# -2x + 3y - 4z = 5
# 4x - 5y + 6z = 11

coeff = np.array([
    [1, 1, -2],
    [-2, 3, -4],
    [4, -5, 6]
])
y = np.array([7, 5, 11])

np.linalg.solve(coeff, y)

array([-14., -65., -43.])

In [26]:
a, b = np.arange(4).reshape((2, 2)), np.arange(2, 6).reshape((2, 2))

print(np.dot(a, b))
print("-"*10)
print(a @ b)

[[ 4  5]
 [16 21]]
----------
[[ 4  5]
 [16 21]]


In [ ]:
arr = np.arange(12).reshape((3, 2, 2))
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [31]:
np.transpose(arr, (1, 2, 0))

array([[[ 0,  4,  8],
        [ 1,  5,  9]],

       [[ 2,  6, 10],
        [ 3,  7, 11]]])