# Numpy

In [ ]:
# install numpy
! pip install numpy

In [ ]:
# import the numpy 
import numpy as np

In [3]:
l = [1, 2, 3, 4]

In [ ]:
# Creating numpy array from sequence (list here)
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [6]:
type(l), type(arr)

(list, numpy.ndarray)

In [ ]:
# Creating numpy array from sequence (tuple here)
np.array((1, 2, 3, 4))

array([1, 2, 3, 4])

In [ ]:
# Check the data type of elements in the numpy array
arr.dtype

dtype('int32')

In [ ]:
# number of dimensions in the numpy array
arr.ndim

1

given matrix <br>
|1 2 3| <br>
|4 5 6| <br>
|7 8 9| <br>

In [12]:
matrix_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# creating numpy array from nested list
arr2 = np.array(matrix_list)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# number of dimensions in the numpy array
arr2.ndim

2

In [ ]:
# shape of the numpy array
arr2.shape

(3, 3)

In [ ]:
# identify the index of the largest element in the numpy array
arr2.argmax()

8

In [ ]:
# identify the index of the smallest element in the numpy array
arr2.argmin()

0

In [19]:
arr2.dtype

dtype('int32')

In [ ]:
# change the data type of elements in numpy array
arr2.astype('float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [29]:
list(range(0, 5, 1))

[0, 1, 2, 3, 4]

In [ ]:
# Create array with arange
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [ ]:
# create equally spaced N (here=5) elements' array in the given range 
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Python's `all()` and `any()`

In [49]:
if 0.2345:
    print("Inside if statement")
else:
    print("Inside else statement")

Inside if statement


In [42]:
l = [True, [], 4]

In [43]:
all(l), any(l)

(False, True)

In [52]:
np.all(arr2), np.any(arr2)

(True, True)

In [ ]:
# create numpy array with 0 as default value
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.zeros((2, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# create numpy array with 1 as default value
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [57]:
arr3 = np.arange(12)
arr3, arr3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [ ]:
# reshaping the array
arr3_r1 = arr3.reshape((2, 6))
arr3_r1, arr3_r1.shape, arr3_r1.ndim

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6),
 2)

In [ ]:
# reshaping the array
arr3_r1 = arr3.reshape((2, 3, 2))
arr3_r1, arr3_r1.shape, arr3_r1.ndim

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 (2, 3, 2),
 3)

In [66]:
arr3_r1[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])