# Broadcasting and Vectorization

In [1]:
2 + 3

5

In [3]:
a, b = [1, 2], [3, 4]
total = []
for i in range(2):
    total.append(a[i] + b[i])

total

[4, 6]

In [5]:
[i + j for i, j in zip(a, b)]

[4, 6]

In [ ]:
[1, 2], [1, 1]

### Broadcasting

In [6]:
import numpy as np

In [13]:
arr1 = np.arange(12).reshape((3, 4))
arr2 = np.arange(4)
print(arr1)
print()
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]


In [14]:
arr1 + arr2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [15]:
arr1 = np.arange(12).reshape((3, 4))
arr2 = np.arange(3)
print(arr1)
print()
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2]


In [16]:
arr2 + arr1

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [17]:
arr1 = np.arange(9).reshape((3, 3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr1 + 100

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [20]:
arr1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [22]:
arr1 / 3

array([[0.        , 0.33333333, 0.66666667],
       [1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667]])

In [23]:
a1 = np.arange(9).reshape((3, 3))
a2 = np.arange(9, 18).reshape((3, 3))
a1, a2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]))

In [24]:
a1 + a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [25]:
a1 = np.arange(4)
a2 = np.arange(4, 8)
a1, a2

(array([0, 1, 2, 3]), array([4, 5, 6, 7]))

In [ ]:
np.dot(a1, a2) # 0*4 + 1*5 + 2*6 + 3*7 = 38

38

In [28]:
a1 = np.arange(9).reshape((3, 3))
a2 = np.arange(9, 27, 2).reshape((3, 3))
a1, a2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]]))

In [29]:
np.dot(a1, a2)

array([[ 57,  63,  69],
       [192, 216, 240],
       [327, 369, 411]])

In [31]:
a1 = np.arange(8).reshape((2, 2, 2))
a2 = np.arange(1, 3)
print(a1, a2)
print(a1.shape, a2.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] [1 2]
(2, 2, 2) (2,)


In [32]:
np.dot(a1, a2)

array([[ 2,  8],
       [14, 20]])

In [33]:
a1 = np.arange(18).reshape((3, 3, 2))
a2 = np.arange(8).reshape((2, 4))
print(a1, a2)
print(a1.shape, a2.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]] [[0 1 2 3]
 [4 5 6 7]]
(3, 3, 2) (2, 4)


In [36]:
np.dot(a1, a2)

array([[[  4,   5,   6,   7],
        [ 12,  17,  22,  27],
        [ 20,  29,  38,  47]],

       [[ 28,  41,  54,  67],
        [ 36,  53,  70,  87],
        [ 44,  65,  86, 107]],

       [[ 52,  77, 102, 127],
        [ 60,  89, 118, 147],
        [ 68, 101, 134, 167]]])

In [38]:
def cube(x: int):
    return x ** 3

for ele in [1, 2, 3]:
    print(cube(ele))

1
8
27


In [40]:
cube_vec = np.vectorize(cube)
cube_vec([1, 2, 3, 4, 5])

array([  1,   8,  27,  64, 125])